{{- if .Values.externalService.enabled -}}

apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.releaseNamePrefix | default .Release.Name }}-flow-agents-external"
  labels:
    app: "{{ .Values.releaseNamePrefix | default .Release.Name }}-flow-agent-service"
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: LoadBalancer
  ports:
    - name: p2
      port: 7800
      protocol: TCP
      targetPort: p4-agent
  selector:
    app: "{{  .Values.releaseNamePrefix | default .Release.Name }}-flow-agent"
    release: {{ .Release.Name }}
{{ end }}
